### ISSUE TITLE
Why is the x/ Y path smooth after I execute the source code, but the video is still unstable？

### ISSUE THREAD

**Issue by corin-lyz** [thejarlid/VideoStabilizationPy#3]
Why is the x/ Y path smooth after I execute the source code, but the video is still unstable？

**Comment by thejarlid** [comment]
This is a known issue the actual generated path is correct which is reflected by the graph however the issue is that my reprojection code which transforms the image is incorrect and needs to be looked at. I currently don't have much time but I will try take a look at it. Thank you for pointing it out!

**Comment by thejarlid** [comment]
This has been resolved now
